---
- name: droplet(s) present
  digital_ocean:
    state: present
    command: droplet
    size_id: 1gb
    region_id: nyc3
    image_id: centos-7-x64
    unique_name: yes
    ssh_key_ids: "{{ vault_do_key_ids }}"
    name: "ace-{{ item }}"
  with_items: "{{ droplets }}"
  register: droplet_info

- name: droplet(s) tagged
  digital_ocean_tag:
    resource_id: "{{ item.droplet.id }}"
    name: ace
  with_items: "{{ droplet_info.results }}"

- name: DNS records added
  cloudflare_dns: 
    zone: "{{ vault_cloudflare_zone }}"
    account_api_token: "{{ vault_cloudflare_token }}"
    account_email: "{{ vault_cloudflare_email }}"
    record: "{{ item.droplet.name }}"
    type: A
    value: "{{ item.droplet.ip_address }}"
    state: present
  with_items: "{{ droplet_info.results }}"
